app:
  environment: prod

images:
  tag: prod

backend:
  replicas: 3
  publicBaseUrl: https://fesko.fun

frontend:
  replicas: 3
  service:
    type: NodePort
    nodePort: 30082

postgres:
  hostPath: /var/lib/url-shortener-postgres-prod
