app:
  environment: dev

images:
  backend: bakr123/short_service
  frontend: bakr123/short_service_client
  tag: latest
  pullPolicy: Always

backend:
  replicas: 2
  port: 3000
  publicBaseUrl: http://localhost
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicas: 2
  port: 80
  service:
    type: ClusterIP
    nodePort: null
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi

postgres:
  image: postgres:16-alpine
  database: shortener
  username: shortener
  password: shortenerpass
  storage: 2Gi
  hostPath: /var/lib/url-shortener-postgres-dev
