apiVersion: v1
kind: Secret
metadata:
  name: short-service-postgres
  namespace: url-shortener
type: Opaque
stringData:
  POSTGRES_DB: short_service
  POSTGRES_USER: short_service
  POSTGRES_PASSWORD: short_service
  DATABASE_URL: postgres://short_service:short_service@postgres:5432/short_service
