apiVersion: v1
kind: ConfigMap
metadata:
  name: short-service-server
  namespace: url-shortener
data:
  PORT: "3000"
  CLIENT_ORIGIN: http://35.194.31.135:30080
  PUBLIC_BASE_URL: http://35.194.31.135:30080
