apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-{{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.postgres.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-{{ .Release.Namespace }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.postgres.hostPath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-{{ .Release.Namespace }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    environment: {{ .Values.app.environment }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        environment: {{ .Values.app.environment }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-1
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U {{ .Values.postgres.username }} -d {{ .Values.postgres.database }}
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
